### ISSUE TITLE
Issue loading AQ data on front page visual

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq.org#345] opened 2019-10-15 15:15 UTC
Someone brought this up the other day and I've noticed it's persisted - looks like the 'AQ comparison visual' on the front page isn't finding any available measurements. Looks like the API is working? So not quite sure what is up.

cc: @jflasher 

![Screen Shot 2019-10-15 at 11 12 41 AM](https://user-images.githubusercontent.com/13404290/66844806-ede82100-ef3c-11e9-831b-01667b00a946.png)

**Comment by RocketD0g** [comment] 2019-10-21 20:34
Also cc'ing @olafveerman in case you might have insight.

**Comment by olafveerman** [comment] 2019-10-21 20:51
cci-ng more people on this thread.
@danielfdsilva join the party.

**Comment by danielfdsilva** [comment] 2019-10-23 10:11
This is working as expected, although "working as expected" may not be good in this situation.

Here's what's happening:
We want to display a chart for PM25 for 7 days with measurements not older than a week. The api has no option to "get locations that have measurements between start and end date" so we resorted to a random probabilistic approach that seemed to be working during development time.
We get a location at random and see if it meets the criteria (last update was within a week), otherwise we try again up to a maximum of 5 times.

Without implementing an api parameter that gives us what we need there's little we can do to truly solve the problem. We could try to mitigate it with:
- Increase the number of tries
- Increase the window of time for when we allow the last measurement to be (say a month)

cc @olafveerman @jflasher @RocketD0g

**Comment by jflasher** [comment] 2019-10-23 11:27
How are we determining the last update time? If it’s coming from the locations table, this may be related to the Athena query to generate that not running at the moment?

**Comment by jflasher** [comment] 2019-10-23 17:43
Closing this as it's not a bug on the front page (unless we want to change the behavior/design). It was due to the Athena queries not running to update locations table (https://github.com/openaq/openaq.org/issues/346)

**Closed by jflasher** 2019-10-23 17:43 UTC
Labels: bug
