### ISSUE TITLE
Advisory Board Content

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq.org#310] opened 2019-08-20 15:03 UTC
We can add in titles for folks, too, if we like, but some are very long.

Note on the headshots:
* I've noted the cases where the headshots are the 'final version'; in all other cases these headshots should be considered placeholders until confirmed by a board member.
* If it'd be helpful for me to fiddle with some re-sizing of the 'final' ones, let me know what dimensions we'd like to use.
* If, at a glance, any of the 'placeholder' headshots look like a complete no-go, let me know.

cc: @olafveerman, @areTey

| Name  |      Org     | Headshot| Final Headshot?|
|----------|:-------------:|------:|------:|
| Michael Brauer, ScD | The University of British Columbia| ![Michael Brauer-0647](https://user-images.githubusercontent.com/13404290/63369241-83a46d00-c34d-11e9-9d6b-4c6e56291f47.jpg)|Y|
| Jessica Lam | ClimateWorks| ![Jess_Lam](https://user-images.githubusercontent.com/13404290/63357481-809e8200-c337-11e9-9000-30ff341bcc88.jpg) |Y|
| Sarath Guttikunda, PhD | Urban Emissions| ![Guttikunda-a](https://user-images.githubusercontent.com/13404290/63441493-8069b980-c3ff-11e9-8b2d-14590319152f.jpg)|Y|
| Romain Lacombe | PlumeLabs | ![Romain Lacombe – Profile – Credit Nacho Bonilla](https://user-images.githubusercontent.com/13404290/64056044-74e46400-cb5e-11e9-8339-aada5922e0bc.jpg) |Y|
| Tom Lee | Mapbox | ![tom_decent_headshot_cropped 2](https://user-images.githubusercontent.com/13404290/63812333-585fe600-c92a-11e9-9b63-aba9700d1070.jpg) |Y|
| Martin Schultz, PhD| Forschungszentrum Jülich  | ![schultz-90_portrait](https://user-images.githubusercontent.com/13404290/63357435-695f9480-c337-11e9-9239-0bd49dfa86fc.jpg) | Y, alternative also available|
| Jessica Seddon, PhD  | World Resources Institute   | ![jessicaseddon](https://user-images.githubusercontent.com/13404290/63358666-6e254800-c339-11e9-9601-b7e07ab6506a.jpeg) |N |
| Douglas Varley, JD | Caplin & Drysdale  | ![dougvarley](https://user-images.githubusercontent.com/13404290/63358966-eab82680-c339-11e9-9817-6973ab8f79b9.jpeg) | N |
| Robin Wilson | Fairfax County Government | ![Robin Wilson pic](https://user-images.githubusercontent.com/13404290/63812502-dde39600-c92a-11e9-80e0-c1eeb0f6b7dc.jpg)| Y |
| Matthew Whitney  | Clean Air Fund |![Matt Headshot](https://user-images.githubusercontent.com/13404290/63443984-c032a000-c403-11e9-8c3c-c4ca56e5056d.PNG)|Y |

**Comment by olafveerman** [comment] 2019-08-20 20:03
Thanks @RocketD0g 
I've added all the profiles, including the headshots that are confirmed. Ultimately, they need to be square, but most of the existing ones will work well. This is the current status:

![image](https://user-images.githubusercontent.com/751330/63380159-e9035880-c363-11e9-9ab1-52813a7ec9cb.png)

**Comment by RocketD0g** [comment] 2019-08-21 14:38
Now wpdated with Sarath Guttikunda's final headshot version.

**Comment by RocketD0g** [comment] 2019-08-21 15:07
Now updated with Matt Whitney's final headshot version.

**Comment by RocketD0g** [comment] 2019-08-27 22:26
Now updated with Tom Lee's final headshot version.

**Comment by RocketD0g** [comment] 2019-08-27 22:29
And _just_ got Robin Wilson's; hers added now too.

**Comment by RocketD0g** [comment] 2019-08-30 23:44
Added Romain's final headshot.

**Comment by RocketD0g** [comment] 2019-08-30 23:44
Noticed I had a typo for Romain's name (NO 'e').

**Comment by jflasher** [comment] 2021-03-07 20:02
Closing this due to age, but can be reopened if community continues to raise as an issue.

**Closed by jflasher** 2021-03-07 20:02 UTC
Labels: v3-redesign
